import argparse

def MF_parse():
    parser = argparse.ArgumentParser(description='hyperparameters')
    parser.add_argument('--num_users', help='...', default=6034, type=int)
    parser.add_argument('--num_items', help='...', default=3533, type=int)
    parser.add_argument('--rec_size', help='...', default=5, type=int)
    parser.add_argument('--lr', help='...', default=0.001, type=float)
    parser.add_argument('--alpha', help='...', default=0, type=float)
    parser.add_argument('--target_item', help='...', default=0, type=int)
    parser.add_argument('--latent_dim_rec', help='...', default=64, type=int)
    parser.add_argument('--boredom_threshold', help='...', default=3, type=int)
    parser.add_argument('--boredom_moving_window', help='...', default=5, type=int)
    parser.add_argument('--optimize_iters', help='...', default=10, type=int)
    parser.add_argument('--env_omega', help='...', default=0.9, type=float)
    parser.add_argument('--env_slope', help='...', default=10, type=float)
    parser.add_argument('--env_offset', help='...', default=0.9, type=float)
    parser.add_argument('--rating_frequency', help='...', default=1, type=float)
    parser.add_argument('--env_embedds', help='...', default='item_embeddings_focused.pt', type=str)
    parser.add_argument('--user_embedds', help='...', default='user_embeddings_pre.pt', type=str)
    parser.add_argument('--device', help='...', default='cpu', type=str)
    parser.add_argument('--episode_length', help='...', default=20, type=int)
    parser.add_argument('--epochs', help='...', default=50, type=int)
    args = parser.parse_args()
    return args

def seq_parse():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dataset', default='simulated_data_2023_9_20')
    parser.add_argument('--train_dir', default='IRS_default')
    parser.add_argument('--batch_size', default=512, type=int)
    parser.add_argument('--lr', default=0.001, type=float)
    parser.add_argument('--maxlen_test', default=60, type=int)
    parser.add_argument('--maxlen', default=60, type=int)
    parser.add_argument('--minlen', default=20, type=int)
    parser.add_argument('--hidden_units', default=30, type=int)
    parser.add_argument('--num_blocks', default=6, type=int)
    parser.add_argument('--num_epochs', default=201, type=int)  
    parser.add_argument('--num_update_lr', default=20, type=int)
    parser.add_argument('--num_heads', default=6, type=int)
    parser.add_argument('--path_len', default=20, type=int)
    parser.add_argument('--dropout_rate', default=0., type=float)
    parser.add_argument('--l2_emb', default=0.0, type=float)
    parser.add_argument('--device', default='cuda:4', type=str)
    parser.add_argument('--num_users', help='...', default=6034, type=int)
    parser.add_argument('--num_items', help='...', default=3533, type=int)
    parser.add_argument('--target_item', help='...', default=1, type=int)
    parser.add_argument('--latent_dim_rec', help='...', default=64, type=int)
    parser.add_argument('--episode_length', help='...', default=20, type=int)
    parser.add_argument('--boredom_threshold', help='...', default=4, type=int)
    parser.add_argument('--boredom_moving_window', help='...', default=5, type=int)
    parser.add_argument('--env_omega', help='...', default=0.9, type=float)
    parser.add_argument('--env_slope', help='...', default=10, type=float)
    parser.add_argument('--env_offset', help='...', default=0.9, type=float)
    parser.add_argument('--env_embedds', help='...', default='item_embeddings_focused.pt', type=str)
    parser.add_argument('--user_embedds', help='...', default='user_embeddings_pre.pt', type=str)
    args = parser.parse_args()
    return args